version: '3'

services:
  nginx:
    image: linuxserver/letsencrypt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - URL=guo.sh
      - SUBDOMAINS=www,
      - VALIDATION=http
      - DNSPLUGIN=cloudflare #optional
      - EMAIL=i@zxguo.me #optional
    volumes:
      - ./nginx:/config
    ports:
      - 443:443
      - 80:80 #optional
    depends_on:
      - web
  web:
    build: web/.
    depends_on:
      - server
  crawler:
    build: crawler/.
    network_mode: "host"
  server:
    build: server/.
    depends_on:
      - elastic
      - redis
    ports:
      - "50051:50051"
  redis:
    image: "redis:alpine"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    expose:
      - "9200"

volumes:
  esdata:
    driver: local
