version: '3'

services:
  server:
    build: server/.
    depends_on:
      - elastic
      - redis
    ports:
    - "50051:50051"
  redis:
    image: "redis:alpine"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    environment:
    - discovery.type=single-node
    ports:
    - "9200:9200"