version: '3'

services:
  web:
    build: web/.
    depends_on:
      - server
    ports:
      "3000:80"
  server:
    build: server/.
    depends_on:
      - elastic
      - redis
    ports:
    - "50051:50051"
  redis:
    image: "redis:alpine"
  elastic:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.8.1"
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

volumes:
  esdata:
    driver: local